spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
  datasource:
    url: jdbc:mysql://47.107.132.207:3306/test?useSSL=false
    username: root
    password: fauingh
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    favicon:
      enabled: false
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: false
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
server:
  port: 80